# just human friendly name for a workflow
name: Terraform Deploy

# trigger, when the job should trigger
on:
    # automated trigger, most of the time it's "git push" event or "merge PR"
    push:
        branches:
        - 'main'
        - 'staging'
        - 'feature/**'
    # manual trigger
    workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

# define the job, what should GitHub run?
jobs:
    deploy:
        environment: dev
        # where should this job run? Azure VM
        runs-on: ubuntu-24.04

        
        steps:

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.5.0

        - name: Clone repo
          uses: actions/checkout@v3

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: us-east-1
            role-to-assume: arn:aws:iam::620676131314:role/Terraform-github-runner-iam-role
            role-session-name: gha-terraform-session   

        - name: Deploy Terraform code
          working-directory: root-project-x/
          run: |
            terraform init -backend-config="bucket=project-x-state"

            # terraform fmt -check
            terraform plan -input=false 

            terraform apply -auto-approve -input=false 